spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/postgres
    username: postgres
    password: 0pus
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
  mvc:
    locale: en_US

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  servlet:
    context-path: /api